version: 1

optuna:
  n_trials: 50
  timeout: null
  pruner: median   # median | nopruner
  metric: f1

spaces:
  xgboost:
    learning_rate: loguniform(1e-3, 0.3)
    n_estimators: int(300, 3000)
    max_depth: int(3, 10)
    min_child_weight: int(1, 10)
    subsample: uniform(0.5, 1.0)
    colsample_bytree: uniform(0.5, 1.0)
    reg_lambda: loguniform(1e-3, 10)
    reg_alpha: loguniform(1e-3, 10)
    gamma: uniform(0.0, 5.0)

  lightgbm:
    learning_rate: loguniform(1e-3, 0.2)
    n_estimators: int(500, 5000)
    num_leaves: int(31, 255)
    max_depth: int(5, 16)
    feature_fraction: uniform(0.6, 1.0)
    bagging_fraction: uniform(0.6, 1.0)
    bagging_freq: int(0, 5)
    min_data_in_leaf: int(10, 200)
    lambda_l1: loguniform(1e-3, 10)
    lambda_l2: loguniform(1e-3, 10)
    min_split_gain: uniform(0.0, 1.0)

  catboost:
    learning_rate: loguniform(1e-3, 0.2)
    iterations: int(500, 5000)
    depth: int(4, 10)
    l2_leaf_reg: loguniform(1.0, 30.0)
    random_strength: uniform(0.0, 1.0)
    bagging_temperature: uniform(0.0, 1.0)


